Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
  config.vm.box = "ubuntu/bionic64"
  ubuntu.vm.network "forwarded_port", guest: 80, host: 8080
  ubuntu.vm.network "forwarded_port", guest: 3306, host: 3306
  ubuntu.vm.synced_folder "/home/nikita/hometask_5"
  ubuntu.vm.provision "shell",
  inline:
    "docker-compose up -d"
  end 
end
